### ISSUE TITLE
[@ninjaprawn] questions about amfid

### ISSUE THREAD

**Issue by AlexeyGorbushin** [ninjaprawn/async_awake-fun#21]
@ninjaprawn. Did you tested inject_amfid? Did you run the apps from the shell on the device?
I opened the shell access to the device and I saw that inject_amfid is in zombie state (see below). Could you explain in details an idea of inject_amfid? 
In my understanding, you try to hook the function MISValidateSignatureAndCopyInfo() in libmis.dylib by means of
remote_write(mach_task_self(), binary_load_address()+patch_offset, (uint64_t)&fake_func_addr, 8); 
to redirect the call to fake_MISValidateSignatureAndCopyInfo() located in amfid_payload.dylib
But how will "amfid" call the fake_MISValidateSignatureAndCopyInfo() located in another address space (in inject_amfid)?  
Also, I didn't notice messages from the amfid_payload.m

  242   ??  SXs    0:02.31 /var/containers/Bundle/Application/F67C6B2C-F295-4442-9B16-81D88984FD3E/async_wake_ios.app/async_wake_ios
  **243   ??  Z      0:00.00 (inject_amfid)**
  244   ??  S      0:00.01 /usr/bin/bash

....

id
uid=0(root) gid=0(wheel) egid=501(mobile) groups=0(wheel),1(daemon),2(kmem),3(sys),4(tty),5(operator),8(procview),9(procmod),20(staff),29(certusers),80(admin)

ls -al
total 3
drwxrwxr-t  20 root  admin   640 Dec 24 14:01 .
drwxrwxr-t  20 root  admin   640 Dec 24 14:01 ..
dr-xr-xr-t@  2 root  wheel    64 Nov 15 03:09 .HFS+ Private Directory Data
-rw-r--r--   1 root  admin     0 Dec 24 14:01 .bit_of_fun
----------   1 root  admin     0 Oct  3 05:38 .file
drwx------   2 root  wheel    64 Sep 30 06:28 .mb
drwxrwxr-x  65 root  admin  2080 Nov 15 03:20 Applications
drwxrwxr-t   8 root  admin   340 Oct 13 11:13 Developer
drwxrwxr-x  19 root  admin   608 Nov 15 03:20 Library
drwxr-xr-x   3 root  wheel    96 Sep 29 23:19 System
drwxr-xr-x   4 root  wheel   128 Nov 15 03:20 bin
drwxrwxr-t   2 root  admin    64 Oct  3 05:38 cores
dr-xr-xr-x   3 root  wheel  1442 Dec 24 22:39 dev
lrwxr-xr-x   1 root  admin    11 Nov 15 03:20 etc -> private/etc
dr----x--x   5 root  admin   160 Dec 24 22:46 fun_bins
drwxr-xr-x   5 root  wheel   160 Dec 13 14:37 private
drwxr-xr-x  14 root  wheel   448 Nov 15 03:20 sbin
lrwxr-xr-x   1 root  admin    15 Nov 15 03:20 tmp -> private/var/tmp
drwxr-xr-x   9 root  wheel   288 Dec 13 14:36 usr
lrwxr-xr-x   1 root  admin    11 Nov 15 03:20 var -> private/var

**Comment by ninjaprawn** [comment]
Hm ok. I didn't expect inject_amfid to be in a zombie state - i guess opening a seperate thread with dlopen still has the constructor running - might look into it, or just turn it into some useful daemon. 

inject_amfid is a simple process that takes in the pid of amfid. it then retrieves the task port of it. Them uses some of ian beers code from triple_fetch to call a function remotely in a process. we can do this since pretty much all functions are loaded in from the dyld_shared_cache, which has a shared address space (for efficiency reasons). We call dlopen in amfid with our own dylib (amfid_payload.dylib). This dylib pretty much just replaces the function pointer to MISValidateSignatureAndCopyInfo with our own. Note that whenever a binary references a function statically, its reference put into a section within the macho, which is what we override.

The reason I can replace the pointer to the real function with my function, and it still works, is because we dlopen'd our dylib in the amfid space, but didnt dlclose it. this means that everything is still "loaded" into amfid's address space - so we can still call it. (however this does mean there is a random handle still in there, but it doesnt really matter)

**Comment by AlexeyGorbushin** [comment]
Nice idea. Thanks for the explanation. Do you have plans to put http://newosxbook.com/files/binpack64.tar in your app? The content of this archive is already signed by SHA-256 and suitable for using in iOS 11

**Comment by AlexeyGorbushin** [comment]
It looks like your injector for amfid doesn't work. I created the test app and run it. 
The test app doesn't run until the hash would not be inserted into the trusted kernel cache.

**Comment by stek29** [comment]
@NewDwarf Why doesn't it work? Make sure your app is arm64 (not FAT), SHA-256 signed and either has platform-application entitlement or is launched by launchd.

**Comment by AlexeyGorbushin** [comment]
Here is the sample code:
cat hello.m 
#import <Foundation/Foundation.h>

```
int main (int argc, const char * argv[])
{
        NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
        NSLog (@"Hello, World!");
        [pool drain];
        return 0;
}
```
Yes, it is thin arm64 app and pseudo-signed (sha-256) by jtool.  

 otool -h hello 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2    20       1880 0x00200085

jtool --sig hello 
Blob at offset: 49648 (624 bytes) is an embedded signature
Code Directory (574 bytes)
		Version:     20001
		Flags:       none
		CodeLimit:   0xc1f0
		Identifier:  hello (0x58)
		CDHash:	     92bf521f43a475303d9d3e3cd65d1bf5fe84ed140b1b457cfa338fa8a8f5c59f (computed)
		# of Hashes: 13 code + 2 special
		Hashes @158 size: 32 Type: SHA-256
 Empty requirement set (12 bytes)

When I run the 'hello' from the main app or from the shell console, 'hello' is killed by the kernel as amfid patched by amfid_payload.dylib returns 'Bad Signature' (I guess).
If I insert the hash into the kernel's trust cache, the 'hello' works fine.

This is a reason why I told that amfid hooking doesn't work.

What was your solution? How did you verify that pseudo signed third party code run fine?

**Comment by stek29** [comment]
@NewDwarf You need platform-application entitlement.

```
$ cat ent.plist
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>platform-application</key>
    <true/>
</dict>
</plist>

$ jtool --sign --inplace --ent ent.plist hello
```

**Comment by AlexeyGorbushin** [comment]
@stek29 Thank you!
